# Generated by Django 5.0.6 on 2024-06-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='query',
            name='msg',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='query',
            name='subject',
            field=models.CharField(max_length=150),
        ),
    ]
