# Generated by Django 5.0.6 on 2024-06-16 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='features',
        ),
        migrations.AddField(
            model_name='brand',
            name='img_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.image'),
            preserve_default=False,
        ),
    ]
