# Generated by Django 5.0.6 on 2024-06-16 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_brand_features_brand_img_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='img_id',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='pro_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='img_id',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='img_id',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='img_id',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='pro_id',
            new_name='product',
        ),
        migrations.DeleteModel(
            name='BrandImage',
        ),
    ]
