# Generated by Django 5.0.6 on 2024-06-18 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_img_id_banner_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datasheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='datasheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.datasheet'),
        ),
    ]
