# Generated by Django 5.0.6 on 2024-06-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='link',
            field=models.CharField(max_length=60),
        ),
    ]
